name: madinaapp
description: My new Flutter app
version: 1.0.2+3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.7
  equatable: ^2.0.5
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  camera: ^0.10.5+5
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/
